#ifndef RES_H
#define RES_H

//original chip8 res is 64x32
#define ORIGINAL_WIDTH 64
#define ORIGINAL_HEIGHT 32

#define SCALE 10

#define SCREEN_WIDTH (ORIGINAL_WIDTH*SCALE)
#define SCREEN_HEIGHT (ORIGINAL_HEIGHT*SCALE)

#define PIXEL_WIDTH (SCREEN_WIDTH / ORIGINAL_WIDTH)
#define PIXEL_HEIGHT (SCREEN_HEIGHT / ORIGINAL_HEIGHT)

#endif
